#!/bin/bash

#Default "latest" tag
docker manifest create \
	$DOCKER_REPO \
	$DOCKER_REPO:$SOURCE_BRANCH-amd64 \
	$DOCKER_REPO:$SOURCE_BRANCH-386 \
	$DOCKER_REPO:$SOURCE_BRANCH-arm

for ARCH in amd64 386 arm
do
docker manifest annotate \
	$DOCKER_REPO \
	$DOCKER_REPO:$SOURCE_BRANCH-$ARCH --os linux --arch $ARCH
done

docker manifest push --purge \
	$DOCKER_REPO

docker manifest inspect \
	$DOCKER_REPO

#Release specific tag
docker manifest create \
	$DOCKER_REPO:$SOURCE_BRANCH \
	$DOCKER_REPO:$SOURCE_BRANCH-amd64 \
	$DOCKER_REPO:$SOURCE_BRANCH-386 \
	$DOCKER_REPO:$SOURCE_BRANCH-arm

for ARCH in amd64 386 arm
do
docker manifest annotate \
	$DOCKER_REPO:$SOURCE_BRANCH \
	$DOCKER_REPO:$SOURCE_BRANCH-$ARCH --os linux --arch $ARCH
done

docker manifest push --purge \
	$DOCKER_REPO:$SOURCE_BRANCH

docker manifest inspect \
	$DOCKER_REPO:$SOURCE_BRANCH